name: Validate Toolbox

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - master

jobs:
  test-toolbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Pull Toolbox Image
        run: docker pull ksandermann/cloud-toolbox:latest

      - name: Run Toolbox Test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ksandermann/cloud-toolbox:latest \
            bash /workspace/toolbox_test.sh